version: '3.1'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
      
  taxi_booking_app:
    image: taxi_booking:v1
    ports: 
        - "8080:8080"
    environment:
        URL: jdbc:postgresql://postgres:5432/postgres
        USERNAME: postgres
        PASSWORD: root