version: '3.1'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  rabbitmq:
    image: rabbitmq:3.11.5-management
    ports:
      - 5672:5672
      - 15672:15672

  taxi_booking_consumer:
    build: ./taxibooking-consumer
    ports:
        - "8080:8080"
    environment:
        DB_URL: jdbc:postgresql://postgres:5432/postgres
        DB_USERNAME: postgres
        DB_PASSWORD: root
        RMQ_USERNAME: guest
        RMQ_PASSWORD: guest
        RMQ_HOST: rabbitmq

  taxi_booking_producer:
    build: ./taxibooking-producer
    ports:
      - "8081:8081"
    environment:
      RMQ_USERNAME: guest
      RMQ_PASSWORD: guest
      RMQ_HOST: rabbitmq