spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: validate

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  format_sql: true


