# Use postgres/example user/password credentials
version: '3.1'

services:

  booking:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    links:
      - booking
    ports:
      - 8081:8080