# Use postgres/example user/password credentials
version: '3.1'

services:

  booking:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080