FROM openjdk:17
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} taxibooking.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/taxibooking.jar", "${DB_PASSWORD}", "${DB_URL}", "${DB_USERNAME}", "${RMQ_PASSWORD}", "${RMQ_USERNAME}", "${RMQ_HOST}"]